# Extend from the official Airflow image
FROM apache/airflow:2.8.2

# Use the root user to install packages
USER root

# Install gcc and build-essential to ensure we have the necessary tools to compile extensions
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
         libpq-dev \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

# Switch back to the airflow user for security reasons
USER airflow

# Update pip to the latest version
RUN pip install --upgrade pip

# Install the additional Python packages
RUN pip install --no-cache-dir -r requirements.txt




